name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH for GitHub
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into server and run commands
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "
          sudo bash -c '
            cd /root/11_email_ai/email_ai_backend
            
            # Pull the latest code
            git pull origin main
            
            # Go one step back and build the backend
            cd ..
            docker compose build backend
            
            # Start the backend in detached mode
            docker compose up backend -d
          '
        "
